### ISSUE TITLE
Cannot be used with API gateway

### ISSUE THREAD

**Issue by westlakem** [alexa/alexa-skills-kit-sdk-for-nodejs#381]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
I should get a successful response from api gateway.

## Current Behavior
In the simulator, I'm getting a "There was a problem with the requested skill's response" response, and when looking at the device log, I'm seeing  `"invocationResponse": null,`

## Possible Solution

No idea

## Steps to Reproduce (for bugs)
create a simple skill with a launch request handler, and wire it with an API gateway.  (I used SAM)
```
const LaunchRequestHandler = {
    canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
    },
    handle(handlerInput) {
        const speechText = 'Thank you for contacting us.  How can I help you today?';

        console.log(handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .withSimpleCard(speechText)
            .getResponse());

        return handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .withSimpleCard(speechText)
            .getResponse();
    },
};
```

I've fixed the handlerInput by changing 

`return handlerInput.requestEnvelope.request.type === 'LaunchRequest';`

to

`return handlerInput.requestEnvelope.body.request.type === 'LaunchRequest';`

but I cannot seem to get the response back to the alexa simulator.

## What have you tried:

```
        return {
            statusCode: 200,
            body: JSON.stringify(handlerInput.responseBuilder
                .speak(speechText)
                .reprompt(speechText)
                .withSimpleCard(speechText)
                .getResponse())
        };  // got same outcome
```
```
     handle(handlerInput, context, callback)
     ...
        callback(null, {
            statusCode: 200,
            body: JSON.stringify(handlerInput.responseBuilder
                .speak(speechText)
                .reprompt(speechText)
                .withSimpleCard(speechText)
                .getResponse())
        }); //undefined method callback
```

## Context
I need to be able to talk to the skill behind an API gateway.

## Your Environment

* ASK SDK for Node.js used: x.x.x
            "ask-sdk-core": "^2.0.3",
            "ask-sdk-model": "^1.2.0"
* Operating System and version: Windows 10

## Node.js and NPM Info
* Node.js version used for development: 8.9.3
* NPM version used for development: 5.6.0

**Comment by ask-sdk** [comment]
HI @westlakem , 

Could you try using the responseHelper in the handlerInput to return a response?  see examples [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Developing-Your-First-Skill).

**Comment by westlakem** [comment]
I search for responsehelper on that page and didn't find anything

**Comment by tianrenz** [comment]
Hi @westlakem , 

Sorry, I meant `handlerInput.responseBuilder`

**Comment by westlakem** [comment]
I have.  It's in the "steps to reproduce" section

**Comment by tianrenz** [comment]
Hi @westlakem , 

the response returned from the handler contains only the `response` part of the body. (see [here](https://developer.amazon.com/fr/docs/custom-skills/request-and-response-json-reference.html)). The SDK will fill in the rest for you (version,  sessionAttributes, etc.)

If you need the access to the full response body, you can see the example [here](https://developer.amazon.com/fr/docs/custom-skills/request-and-response-json-reference.html). 

```
const responseEnvelope = await skill.invoke(event, context);
```

Then you can wrap the `responseEnvelope` into your lambda response body. 

Regards,

**Comment by westlakem** [comment]
That doesn't help me.  The return from the handler is an invalid format for
api gateway.  Just put the lambda behind an api gateway and hit it from the
Alexa skill builder "test" and you'll see what issues I'm having.

**Comment by tianrenz** [comment]
Hi @westlakem , 

It would be very helpful if you could post code snippet of your lambda handler here. I'll try to replicate the error. Thanks!

Regards

**Comment by westlakem** [comment]
@tianrenz @ask-sdk This is a SAM project.  I had to change how we got the incoming body from the docs, which makes me think how the result is being returned isn't formatted properly for API Gateway

index.js
```
const alexaApp = require('./alexa-skill')
const googleApp = require('./actions-on-google')

exports.actionsOnGoogle = googleApp.actionsOnGoogle
exports.aws = alexaApp.skillBuilder
```
alexa-skill.js
```
const Alexa = require('ask-sdk-core');
const responses = require('./responses');
const skillBuilder = Alexa.SkillBuilders.custom();
const alexaUtils = require('./alexa-util')

const LaunchRequestHandler = {
    canHandle(handlerInput) {
        requestBody = JSON.parse(handlerInput.requestEnvelope.body);
        return requestBody.request.type === 'LaunchRequest')
    },
    handle(handlerInput) {
        const speechText = 'Thank you for contacting us.  How can we help you today?';

        console.log(handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .withSimpleCard(speechText)
            .getResponse());

        return handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .withSimpleCard(speechText)
            .getResponse();
    },
};
```
assistant.yml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 180
Resources:
  Alexa:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.aws
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /alexa
            Method: post
  ActionsOnGoogle:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.actionsOnGoogle
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /actionsOnGoogle
            Method: post
```
